title: Home

resources:
  - type: module
    url: /community_plugin/button-card/button-card.js
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - type: module
    url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
  - type: module
    url: /community_plugin/simple-thermostat/simple-thermostat.js
  - type: module
    url: /community_plugin/lovelace-card-mod/card-mod.js
  - type: js
    url: /community_plugin/calendar-card/calendar-card.js
    
views:
  - !include lovelace/main.yaml
  - !include lovelace/lights.yaml
#  - !include lovelace/climate.yaml
  - !include lovelace/system.yaml