alias: System if Tado is home turn off vacationmode
description: ''
mode: single
trigger:
  - platform: state
    entity_id: sensor.verwarming_tado_mode
    from: AWAY
    to: HOME
condition: []
action:
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.turn_on_vacationmode