alias: Lights turn on before sunset
description: '30 minutes before sunset'
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30'
condition: []
action:
  - service: light.turn_on
    data:
      brightness: 255
      color_temp: 370
      entity_id:
        - light.keuken_strip
  - service: light.turn_on
    data:
      brightness: 25
      color_temp: 366
      transition: 900
      entity_id:
        - light.woonkamer_voor
  - service: light.turn_on
    data:
      brightness: 25
      transition: 900
      entity_id:
        - light.kleine_lamp
mode: single
