alias: Lights office normal scene
description: 'Turn lights into normal when doors are closed'
trigger:
  - platform: state
    entity_id: group.all_doorsensors
    to: "off"
condition:
  - condition: state
    entity_id: light.strip_office
    state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.sunset
mode: single