alias: Lights turn off all
description: 'If vacationmode is on turn off at 23:30'
mode: single
trigger:
  - platform: time
    at: '23:30'
condition:
  - condition: state
    entity_id: input_boolean.turn_on_vacationmode
    state: 'On'
  - condition: state
    entity_id: binary_sensor.weekend_days
    state: 'On'
action:
  - service: light.turn_off
    data: {}
    entity_id: 'group.all_lights, light.keuken'