alias: Lights office warning scene
description: 'Turn lights into red when doors are open'
trigger:
  - platform: state
    entity_id: group.all_doorsensors
    to: "on"
condition:
  - condition: state
    entity_id: light.strip_office
    state: 'on'
action:
  - service: scene.turn_on
    entity_id: scene.warning
mode: single
